### ISSUE TITLE
Color improvement

### ISSUE THREAD

**Issue by seagle0128** [dracula/mintty#2]
I found these colors are not good for mintty. I adjust as below and it looks better.

```
Black=40,42,54
BoldBlack=80,84,108
```

Otherwise, zsh (with zsh-autosuggestion) and tmux (with Darcula-theme in Emacs) are ugly.

**Comment by Johnson9009** [comment]
@seagle0128 You can try the latest version, this color is set to 104, 104, 104 refer to the setting of iTerm2. Thanks.

**Comment by seagle0128** [comment]
Thanks. Close it.
